### ISSUE TITLE
Change the look on the frontpage 

### ISSUE THREAD

**Issue by dersand** [pajlada/pajbot#199]
The design on the frontpage could use a redesign. [Here is my suggestion.](http://i.imgur.com/fkoafWt.png) 

inside ```  <div class="main container"></div>```
``` HTML
<p class="mainHeader" style="font-size: 1.4em;">
<strong id="broadcasterName">Forsen</strong> 
is 
<span id="streamerLive">LIVE</span>
with currently 
<strong id="viewers">123 420</strong>
viewers 
</p>
<p class="quest">Today's quest:<strong>
SAMPLE TEXT BOTTOM KEK</strong>
</p>
<hr>
  <span id="broadcasterName">Forsen</span>
  the roleplayer can be found here:
<div class="socials">
  <span id="twitch" class="button">Twitch/<strong id="twitchhandle">Forsenlol</span></strong >
    <span id="twitter" class="button">Twitter/<strong id="twitterhandle">@ForsenSC2</strong ></span>
  	<div class="otherSocials">
      <span>Also check out these:</span>
      <div style="margin-top: 1%;">
        <span class="button">Reddit<strong>/r/forsen</strong ></span>
      </div>
  </div>
</div>

<h5>
This is the website for <strong>snusbot</strong> that runs in <a href="http://twitch.tv/forsenlol">Forsen's</a> channel.
</h5>
<h6>
(c) Pajlada no copy pasterino 
</h6>

```

``` CSS
/* Title bar*/
.main > .mainHeader > #streamerLive
{
    color: rgba(11,138,45,1);
    font-size: 1.2em;
    text-decoration: underline;
    font-weight: bold;
}

/* Socials */
.main .button
{
     border: 1px solid black;
     padding: 0.5%;
}

.main > .socials > .otherSocials
{
    margin-top: 1%;
}
.main > .socials > .otherSocials > span
{
    margin-top: 1%;
}


```
